# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#

language: python
python:
  - "2.7"
sudo: true
# Blacklist
branches:
  except:
    - gh-pages
# Environment variables
env:
  global:
    - GH_REPO_NAME: WIFIOnOff
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/peastone/WIFIOnOff.git
cache:
  directories:
    - "~/.platformio"
# Install dependencies
addons:
  apt:
    packages:
      - graphviz
      - cmake3
      - ghostscript
      - latex-xcolor
      - texlive-extra-utils
      - texlive-font-utils
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-generic-recommended
install:
  - pip install -U platformio
  - platformio update
script:
  - platformio ci --project-conf=platformio.ini src

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod u+x doc/generateDocumentationAndDeploy.sh
  - ./doc/generateDocumentationAndDeploy.sh
